### ISSUE TITLE
support kbd tags

### ISSUE THREAD

**Issue by Stwissel** [rjeschke/txtmark#21]
Like Stackoverflow and Github (the stackoverflow are prettier)

**Comment by rjeschke** [comment]
You can always use inline HTML:

    final String markdown = "Do not press <kbd>Alt</kbd>+<kbd>F4</kbd> now!";
    final String result = Processor.process(markdown);
    System.out.println(result);

Will print:

    <p>Do not press <kbd>Alt</kbd>+<kbd>F4</kbd> now!</p>

I did not find anything about having specific markdown tags/elements to support this feature neither on GitHub nor Stackoverflow. Do you have an links to what you mean exactly?

**Comment by Stwissel** [comment]
I think the example I saw used inline html for <kbd>keyboard</kbd> too. Just checked the doku and couldn't find any simpler one. I'm cool with the line HTML
