### ISSUE TITLE
Safe mode is not enough to be really safe

### ISSUE THREAD

**Issue by FroMage** [rjeschke/txtmark#22]
It currently allows users to "escape" the place they are supposed to be at with for example the following HTML template:

```html
<p>
 This contains the text: 
 <div id="user-content">${mdContent}</div>
</p>
```

One can then create Markdown content such as:

```
In the box
</div></p>
<p>
 Outside the box, looks like part of the site now 
 <a href="malicious-link">go there to reset your password please</a>
</p>
```

I need a way to escape every unescaped `<` character from the input.

**Comment by rjeschke** [comment]
Added a *panicMode*, fixed with 00fa65a963e18370569ddc73423511b85e01e0aa

**Comment by FroMage** [comment]
Thanks! I'll try it out!

**Comment by FroMage** [comment]
Yes, works, thanks!
