### ISSUE TITLE
Line break results in /> instead of <br/>

### ISSUE THREAD

**Issue by albert-kam** [rjeschke/txtmark#24]
Configuration configuration = Configuration.builder()
		.enableSafeMode()
		.build();
	String markdown = "Hello **world**  \nThis should come after newline";
	String result = Processor.process(markdown, configuration);
	System.out.println(result);

The output is this :

	<p>Hello <strong>world</strong>  />
	This should come after newline</p>

The expected result is this :

	<p>Hello <strong>world</strong>  <br/>
	This should come after newline</p>

**Comment by rjeschke** [comment]
Fixed with 184a26229aa93db5652d534c7acb366f08f8376e
