### ISSUE TITLE
maven not up to date

### ISSUE THREAD

**Issue by mschipperheyn** [rjeschke/txtmark#27]
The maven repository dates back two years ago. 

Are you not publishing there anymore or are you not publishing snapshots? Both are highly appreciated

**Comment by rjeschke** [comment]
If you look at the commit history, you see that the last commit (before the latest pull request, that only affects source builds with Java8) was the relase of txtmark-11. There hasn't been any changes since then, so I did not need to release a snapshot or anything in between.

**Comment by rjeschke** [comment]
As it looks right now, I will make a few minor changes (adressing some issues) and the release a new version to Central.
