### ISSUE TITLE
Triple backtick (```) code blocks

### ISSUE THREAD

**Issue by nindalf** [rjeschke/txtmark#28]
Is there a plan to support Girhub style triple back ticks for code blocks? It seems that it does not work at the moment. 

I'd be happy to add it if you could give me some guidance on how to start. 
Thanks

**Comment by rjeschke** [comment]
They are already supported when you activate the `extended` mode.

This reminds me that the README isn't up to date.

**Comment by rjeschke** [comment]
So, updated README accordingly, have a look there for how to use fenced code blocks.

**Comment by nindalf** [comment]
Thanks a lot! :)
