### ISSUE TITLE
target="_blank" for links

### ISSUE THREAD

**Issue by mathieuleclaire** [rjeschke/txtmark#40]
Hi,
First, congrats for your simple and efficient tool !
Is it possible to generate all links with the target="_blank". Is there any configuration trick to achieve this ?

Thanks !
Mathieu

**Comment by rjeschke** [comment]
This should be possible by extending `DefaultDecorator` and overwrite [DefaultDecorator#openLink](https://github.com/rjeschke/txtmark/blob/master/src/main/java/com/github/rjeschke/txtmark/DefaultDecorator.java#L219) to append `"<a target=\"_blank\""`.
You can then set the `Decorator` using `Configuration`.

**Comment by mathieuleclaire** [comment]
It works ! Thank you !

**Comment by hellokaton** [comment]
@rjeschke tanks, how to extend the use of?
