### ISSUE TITLE
code block problem

### ISSUE THREAD

**Issue by ghost** [rjeschke/txtmark#46]
This code block does not work properly:

![markdown_codeblock](https://cloud.githubusercontent.com/assets/12461360/10189982/532a6020-6772-11e5-8f6b-3897f8d2ffe0.png)

**Comment by rjeschke** [comment]
Did you enabled the `extended profile`?

See [here](https://gist.github.com/rjeschke/8ba48182d62124335f51) for an example.

_(When I replace the example text in the gist with your text, everything works fine)_

**Comment by ghost** [comment]
Sorry. With extended profile it works.
